config/routes.rb
Srsfda::Application.routes.draw do
  

  get "home/disaster"
  get "home/apps"
  get "home/resources"
  get "home/network"
  get "home/aboutus"
  get "home/contact"
  get "home/work"
  get "home/valanteer"
  get "home/directory"
  resources :advertisements do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

  resources :news do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end


  resources :articles do
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

   resources :jobs do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
    get 'slider', on: :collection
  end


  get "optional/index"
  get "users/profile"
  get "users/index"
  get "users/show"
   get "users/settings"
  get "reports/index"
  get 'reports/db_upload'
    resources :reports
  #devise_for :users
  devise_for :users, controllers: { registration: 'registrations' }
  get "welcome/index"

   root 'jobs#slider'
   #root 'welcome#dashboard'
   get 'welcome/dashboard'
   get 'welcome/screener'
   get 'welcome/analytics'
   get 'welcome/optional'

   get '/users/subregion_options' => 'users#subregion_options'
   get '/payments/complete_payment' => 'payments#complete_payment'

resources :optionals do
  collection { post :import }
end 

resources :products do
  collection { post :import }
end 
resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
   resources :carts do
    collection do
      
      get :license_agrement
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
     if user.role? :user
        can :manage, Post
      end
      if user.role? :admin
        can :manage, ForumThread
      end
      if user.role? :superadmin
        can :manage, Forum
      end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end


end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
	belongs_to :user
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/article.rb
class Article < ActiveRecord::Base
	  belongs_to :user

	  
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/cities.rb
class Cities < ActiveRecord::Base
	belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :user


	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_many :news
    has_many :jobs
    has_many :advertisements
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def disaster
  end

  def apps
  end

  def resources
  end

  def network
  end

  def aboutus
  end

  def contact
  end

  def work
  end

  def valanteer
  end

  def directory
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  respond_to :html



def my
    @jobs = Job.all
    #respond_with(@articles)
  end


def all
    @jobs = Job.all
    #respond_with(@articles)
  end
  def slider
    @jobs = Job.all
    #respond_with(@articles)
  end


   def preview
    @jobs = Job.all
    #respond_with(@articles)
  end



  def index
    @jobs = Job.all
    respond_with(@jobs)
  end

  def show
    respond_with(@job)
  end

  def new
    @job = Job.new
      respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
      format.js
    end
  end

  def edit
  end

  def create
    @job = Job.new(job_params.merge(user_id: current_user.id))
    @job.save
    respond_with(@job)
  end

  def update
    @job.update(job_params)
    respond_with(@job)
  end

  def destroy
    @job.destroy
    respond_with(@job)
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:company_name, :hiring_description, :company_url, :job_location, :email, :display_at, :approve, :avatar, :user_id, :tittle, :keys)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  respond_to :html


def my
    @news = News.all
    #respond_with(@articles)
  end


def all
    @news = News.all
    #respond_with(@articles)
  end


   def preview
    @news = News.all
    #respond_with(@articles)
  end

  def index
    @news = News.all
    respond_with(@news)
  end

  def show
    respond_with(@news)
  end

  def new
    @news = News.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
      format.js
    end
  end

  def edit
  end

  def create
    @news = News.new(news_params.merge(user_id: current_user.id))
    @news.save
    respond_with(@news)
  end

  def update
    @news.update(news_params)
    respond_with(@news)
  end

  def destroy
    @news.destroy
    respond_with(@news)
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:heading, :news, :approve, :description, :avatar, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/optional_helper.rb
module OptionalHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_all.html.erb
<br/><br/>
  <% @jobs.each do |job| %>
    <% if job.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag job.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= job.company_name %></h4>
          <%= truncate job.hiring_description, length: 160 %>
          <%#= job.job %><br/><br/>
          <%=l job.created_at %>&nbsp; by &nbsp;
          <%= job.user.name.upcase %>
          <%= link_to "Read more", job_path(job), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  
<div class="control-group">
    <%= f.label :Logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar %>
    </div>
    <%#= error_span(@article[:avatar_file_name]) %>
  </div>

  
  <div class="control-group">
    <%= f.label :company, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :company_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :job_tittle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tittle, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :hiring_description, :rows => 10 %>
    </div>
  </div>

  
  <div class="control-group">
    <%= f.label :skills_required, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :keys, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :company_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :company_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :job_location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :job_location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :display_at, :class => 'control-label' %>
    <div class="controls">
    <% if user_signed_in? && current_user.role == "admin"%>
     <%= f.text_field :display_at, :class => 'text_field' %>
     <% else %>
      <%= f.select :display_at, options_for_select(%w[ Jobs home ]) %><br/>`Select Home for Display Your Add at Home page, Or It will display at Adds Page...
      <% end %>
    </div>
  </div>
  <% if user_signed_in? && current_user.role == "admin"%>
  <div class="control-group">
    <%= f.label :approve, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :approve , options_for_select(%w[ No Yes ]) %>
    </div>
  </div>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                jobs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/jobs/_my.html.erb
<br/><br/>
  <% current_user.jobs.each do |job| %>
    <%# if job.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag job.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= job.company_name %></h4>
          <%= truncate job.hiring_description, length: 160 %>
          <%#= job.job %><br/><br/>
          <%=l job.created_at %>
          <%= link_to "Read more", job_path(job), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <%# end %>
 <% end %>

app/views/jobs/_preview.html.erb
<% if user_signed_in? && current_user.role == "admin"%>

<br/><br/>


  <% @jobs.each do |job| %>
    <% if job.approve == "No"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag job.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= job.company_name %></h4>
          <%= truncate job.hiring_description, length: 160 %>
          <%#= job.job %><br/><br/>
          <%=l job.created_at %>
          <%= link_to "Read more", job_path(job), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %> <% end %>
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>
 <% end %>

app/views/jobs/all.js.erb
$(".box3").html("<%= escape_javascript(render("/jobs/all")) %>");

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<style type="text/css">
  .readmore{
    padding-left: 250px;
  }
  .jobalign{
padding-bottom: 6px;
padding-left: 160px;
width: 70%;
}
hr {
  width: 80%;
margin: 20px 0;
border: 0;
border-top: 1px solid #46556E;
border-bottom: 1px solid #ffffff;
}
.row-fluid .span10 {
width: 60.90598290598291%;
}

</style>

<div style="width: 900px; height:auto; margin-left: 15%;">

<%- model_class = Job -%>

<div style="width: 900px; height:auto; margin-left: 15%;">


<br/><br/>


  <% @jobs.each do |job| %>
    <% if job.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag job.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= job.company_name %></h4>
          <%= truncate job.hiring_description, length: 160 %>
          <%#= job.job %><br/><br/>
          <%=l job.created_at %>&nbsp; by &nbsp;
          <%= job.user.name.upcase %>
          <%= link_to "Read more", job_path(job), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>
   

app/views/jobs/my.js.erb
$(".box3").html("<%= escape_javascript(render("/jobs/my")) %>");

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/new.js.erb
$(".box3").html("<%= escape_javascript(render("/jobs/new")) %>");

app/views/jobs/preview.js.erb
$(".box3").html("<%= escape_javascript(render("/jobs/preview")) %>");

app/views/jobs/show.html.erb
<style type="text/css">

 .row-fluid {
width: 50%;
padding-left: 180px;
}

.page-header {
padding-bottom: 9px;
margin: 20px 187px 26px;
border-bottom: 1px solid #eeeeee;
}


</style>


<%- model_class = Job -%>


<div class="page-header">
  <h1><%= @job.company_name %></h1>
</div>
<div class ="row-fluid">
<div class = "span6">
  <%= image_tag @job.avatar.url, :style => "width: 200px; height: 200px;" %>
  </div>
  <div class="span6">
  <h8 class="text-justify"><%= @job.tittle %></h8><hr/>
  <p class="text-justify"><%= @job.hiring_description %></p><br/>
  
  </div>

</div>

 
<dl class="dl-horizontal" style="padding-left: 360px;">
<dt><strong><%= model_class.human_attribute_name(:keys) %>:</strong></dt>
  <dd><%= @job.keys %></dd>

  <dt><strong><%= model_class.human_attribute_name(:company_url) %>:</strong></dt>
  <dd><%= @job.company_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_location) %>:</strong></dt>
  <dd><%= @job.job_location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @job.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:display_at) %>:</strong></dt>
  <dd><%= @job.display_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:approve) %>:</strong></dt>
  <dd><%= @job.approve %></dd>
</dl>





<% if current_user %>
<div class="back" style="padding-left: 642px;">
<%= link_to "Back", welcome_dashboard_path, :class => 'btn'%>
</div>
<% else %>
  <%= link_to "Back",jobs_path%>
<% end %>
  <%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn' %>
  <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/news/_all.html.erb
<br/><br/>
  <% @news.each do |news| %>
    <% if news.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag news.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= news.heading %></h4>
          <%= truncate news.news, length: 160 %>
          <%#= news.news %><br/><br/>
          <%=l news.created_at %>&nbsp; by &nbsp;
          <%= news.user.name.upcase %>
          <%= link_to "Read more", news_path(news), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_news_path(news), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      news_index_path(news),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_news_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>

app/views/news/_form.html.erb
<%= form_for @news, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :heading, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :heading, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :avatar_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar %>
    </div>
    <%#= error_span(@article[:avatar_file_name]) %>
  </div>
<% if user_signed_in? && current_user.role == "admin"%>
  <div class="control-group">
    <%= f.label :approve, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :approve, options_for_select(%w[No Yes]) %>
    </div>
  </div>
<% end %>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                news_index_path, :class => 'btn' %>
  </div>
<% end %>

app/views/news/_my.html.erb
<br/><br/>
  <% current_user.news.each do |news| %>
    <%# if news.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag news.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= news.heading %></h4>
          <%= truncate news.news, length: 160 %>
          <%#= news.news %><br/><br/>
          <%=l news.created_at %>
          <%= link_to "Read more", news_path(news), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_news_path(news), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      news_index_path(news),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_news_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <%# end %>
 <% end %>

app/views/news/_preview.html.erb
<% if user_signed_in? && current_user.role == "admin"%>

<br/><br/>


  <% @news.each do |news| %>
    <% if news.approve == "No"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag news.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= news.heading %></h4>
          <%= truncate news.news, length: 160 %>
          <%#= news.news %><br/><br/>
          <%=l news.created_at %>
          <%= link_to "Read more", news_path(news), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_news_path(news), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      news_index_path(news),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_news_path,
            :class => 'btn btn-primary' %> <% end %>
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>
 <% end %>

app/views/news/index.html.erb
<style type="text/css">
  .readmore{
    padding-left: 250px;
  }
  .articlealign{
padding-bottom: 6px;
padding-left: 160px;
width: 70%;
}
hr {
  width: 80%;
margin: 20px 0;
border: 0;
border-top: 1px solid #46556E;
border-bottom: 1px solid #ffffff;
}
.row-fluid .span10 {
width: 60.90598290598291%;
}

</style>

<div style="width: 900px; height:auto; margin-left: 15%;">

<%- model_class = News -%>

<div style="width: 900px; height:auto; margin-left: 15%;">


<br/><br/>


  <% @news.each do |news| %>
    <% if news.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag news.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= news.heading %></h4>
          <%= truncate news.news, length: 160 %>
          <%#= news.news %><br/><br/>
          <%=l news.created_at %>&nbsp; by &nbsp;
          <%= news.user.name.upcase %>
          <%= link_to "Read more", news_path(news), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_news_path(news), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      news_path(news),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_news_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>
   

app/views/news/show.html.erb
<style type="text/css">

 .row-fluid {
width: 50%;
padding-left: 180px;
}

.page-header {
padding-bottom: 9px;
margin: 20px 187px 26px;
border-bottom: 1px solid #eeeeee;
}


</style>


<%- model_class = News -%>


<div class="page-header">
  <h1><%= @news.heading %></h1>
</div>
<div class ="row-fluid">
<%= image_tag @news.avatar.url, :style => "width: 300px; height: 300px;", :ALIGN =>"Left" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @news.description %><br/><br/>



  
<% if current_user %>
<%= link_to "Back",welcome_dashboard_path, :class => "btn"%>
<% else %>
  <%= link_to "Back",news_index_path, :class => "btn"%>
<% end %>
  <%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_news_path(@news), :class => 'btn' %>
  <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              news_path(@news),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>