config/routes.rb
Srsfda::Application.routes.draw do
  

  get "home/disaster"
  get "home/apps"
  get "home/resources"
  get "home/network"
  get "home/aboutus"
  get "home/contact"
  get "home/work"
  get "home/valanteer"
  get "home/directory"
  resources :advertisements do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

  resources :news do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end


  resources :articles do
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

   resources :jobs do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
    get 'slider', on: :collection
  end


  get "optional/index"
  get "users/profile"
  get "users/index"
  get "users/show"
   get "users/settings"
  get "reports/index"
  get 'reports/db_upload'
    resources :reports
  #devise_for :users
  devise_for :users, controllers: { registration: 'registrations' }
  get "welcome/index"

   root 'jobs#slider'
   #root 'welcome#dashboard'
   get 'welcome/dashboard'
   get 'welcome/screener'
   get 'welcome/analytics'
   get 'welcome/optional'

   get '/users/subregion_options' => 'users#subregion_options'
   get '/payments/complete_payment' => 'payments#complete_payment'

resources :optionals do
  collection { post :import }
end 

resources :products do
  collection { post :import }
end 
resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
   resources :carts do
    collection do
      
      get :license_agrement
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
     if user.role? :user
        can :manage, Post
      end
      if user.role? :admin
        can :manage, ForumThread
      end
      if user.role? :superadmin
        can :manage, Forum
      end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end


end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
	belongs_to :user
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/article.rb
class Article < ActiveRecord::Base
	  belongs_to :user

	  
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/cities.rb
class Cities < ActiveRecord::Base
	belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :user


	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_many :news
    has_many :jobs
    has_many :advertisements
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  respond_to :html



def my
    @advertisements = Advertisement.all
    #respond_with(@articles)
  end

   def all
    @advertisements = Advertisement.all
    #respond_with(@articles)
  end


   def preview
    @advertisements = Advertisement.all
    #respond_with(@articles)
  end

  def index
    @advertisements = Advertisement.all
    respond_with(@advertisements)
  end

  def show
    respond_with(@advertisement)
  end

  def new
    @advertisement = Advertisement.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
      format.js
    end
  end

  def edit
  end

  def create
    @advertisement = Advertisement.new(advertisement_params.merge(user_id: current_user.id))
    @advertisement.save
    respond_with(@advertisement)
  end

  def update
    @advertisement.update(advertisement_params)
    respond_with(@advertisement)
  end

  def destroy
    @advertisement.destroy
    respond_with(@advertisement)
  end

  private
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    def advertisement_params
      params.require(:advertisement).permit(:add_heading, :add_description, :display_at, :approve, :avatar, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def disaster
  end

  def apps
  end

  def resources
  end

  def network
  end

  def aboutus
  end

  def contact
  end

  def work
  end

  def valanteer
  end

  def directory
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/optional_helper.rb
module OptionalHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/_all.html.erb
<br/><br/>
  <% @advertisements.each do |advertisement| %>
    <% if advertisement.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag advertisement.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= advertisement.add_heading %></h4>
          <%= truncate advertisement.add_description, length: 160 %>
          <%#= advertisement.advertisement %><br/><br/>
          <%=l advertisement.created_at %>&nbsp; by &nbsp;
          <%= advertisement.user.name.upcase %>
          <%= link_to "Read more", advertisement_path(advertisement), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_advertisement_path(advertisement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advertisement_path(advertisement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_advertisement_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>

app/views/advertisements/_form.html.erb
<%= form_for @advertisement, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :add_heading, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :add_heading, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :add_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :add_description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :display_at, :class => 'control-label' %>
    <div class="controls">
      <% if user_signed_in? && current_user.role == "admin"%>
    <%= f.text_field :display_at, :class => 'text_field' %>
    <% else%>
      <%= f.select :display_at, options_for_select(%w[ Adds home ]) %><br/>Select Home for Display Your Add at Home page, Or It will display at Adds Page...
    <% end%>
    </div>
  </div>
    

   <div class="control-group">
    <%= f.label :avatar_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <% if user_signed_in? && current_user.role == "admin"%>
  <div class="control-group">
    <%= f.label :approve, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :approve , options_for_select(%w[ No Yes ]) %>
    </div>
  </div>
 <% end %>
  

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                advertisements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/advertisements/_my.html.erb
<br/><br/>
  <% current_user.advertisements.each do |advertisement| %>
    <%# if advertisement.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag advertisement.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= advertisement.add_heading %></h4>
          <%= truncate advertisement.add_description, length: 160 %>
          <%#= advertisement.advertisement %><br/><br/>
          <%=l advertisement.created_at %>
          <%= link_to "Read more", advertisement_path(advertisement), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_advertisement_path(advertisement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advertisement_path(advertisement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_advertisement_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <%# end %>
 <% end %>

app/views/advertisements/_new.html.erb
<br/><br/>
<%= form_for @advertisement, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :add_heading, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :add_heading, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :add_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :add_description, :rows => 10 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :display_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :display_at, options_for_select(%w[ Adds home ]) %><br/>Select Home for Display Your Add at Home page, Or It will display at Adds Page...
    </div>
  </div>


   <div class="control-group">
    <%= f.label :avatar_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <% if user_signed_in? && current_user.role == "admin"%>
  <div class="control-group">
    <%= f.label :approve, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :approve , options_for_select(%w[ No Yes ]) %>
    </div>
  </div>
 <% end %>
  

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                advertisements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/advertisements/_preview.html.erb
<% if user_signed_in? && current_user.role == "admin"%>

<br/><br/>


  <% @advertisements.each do |advertisement| %>
    <% if advertisement.approve == "No"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag advertisement.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= advertisement.add_heading %></h4>
          <%= truncate advertisement.add_description, length: 160 %>
          <%#= advertisement.advertisement %><br/><br/>
          <%=l advertisement.created_at %>
          <%= link_to "Read more", advertisement_path(advertisement), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_advertisement_path(advertisement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advertisement_path(advertisement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_advertisement_path,
            :class => 'btn btn-primary' %> <% end %>
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>
 <% end %>

app/views/advertisements/all.js.erb
$(".box3").html("<%= escape_javascript(render("/advertisements/all")) %>");

app/views/advertisements/edit.html.erb
<%- model_class = Advertisement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/advertisements/index.html.erb
<style type="text/css">
  .readmore{
    padding-left: 200px;
  }
  .advertisementalign{
padding-bottom: 6px;
padding-left: 160px;
width: 70%;
}
hr {
  width: 80%;
margin: 20px 0;
border: 0;
border-top: 1px solid #46556E;
border-bottom: 1px solid #ffffff;
}
.row-fluid .span10 {
width: 60.90598290598291%;
}

</style>

<div style="width: 900px; height:auto; margin-left: 15%;">

<%- model_class = Advertisement -%>

<div style="width: 900px; height:auto; margin-left: 15%;">


<br/><br/>


  <% @advertisements.each do |advertisement| %>
    <% if advertisement.approve == "Yes"%>
      <div class="row-fluid">
        <div class="span2">
        <%= image_tag advertisement.avatar.url, :style => "width: 100px; height: 90px;"%>
        </div>
        <div class="span10">
          <h4><%= advertisement.add_heading %></h4>
          <%= truncate advertisement.add_description, length: 160 %>
          <%#= advertisement.advertisement %><br/><br/>
          <%=l advertisement.created_at %>&nbsp;  by 
          <%= advertisement.user.name.upcase %>
          <%= link_to "Read more", advertisement_path(advertisement), :class => "readmore" %><br/><br/>
          <% if user_signed_in? && current_user.role == "admin"%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_advertisement_path(advertisement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advertisement_path(advertisement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%#= link_to t('.new', :default => t("helpers.links.new")),
            new_advertisement_path,
            :class => 'btn btn-primary' %>
            <% end %> 
        </div>
        </div>
 <hr/>
 <% end %>
 <% end %>
   

app/views/advertisements/my.js.erb
$(".box3").html("<%= escape_javascript(render("/advertisements/my")) %>");

app/views/advertisements/new.html.erb
<%- model_class = Advertisement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/advertisements/new.js.erb
$(".box3").html("<%= escape_javascript(render("/advertisements/new")) %>");

app/views/advertisements/preview.js.erb
$(".box3").html("<%= escape_javascript(render("/advertisements/preview")) %>");

app/views/advertisements/show.html.erb
<style type="text/css">

 .row-fluid {
width: 50%;
padding-left: 180px;
}

.page-header {
padding-bottom: 9px;
margin: 20px 187px 26px;
border-bottom: 1px solid #eeeeee;
}


</style>


<%- model_class = Advertisement -%>


<div class="page-header">
  <h1><%= @advertisement.add_heading  %></h1>
</div>
<div class ="row-fluid">
<div class = "span6">
  <%= image_tag @advertisement.avatar.url, :style => "width: 300px; height: 300px;" %>
  </div>
  <div class="span6">
  <p class="text-justify"><%= @advertisement.add_description %></p>
  </div>
  
<% if current_user %>
<%= link_to "Back",welcome_dashboard_path%>
<% else %>
  <%= link_to "Back",articles_path%>
<% end %>
  <%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>