config/routes.rb
Srsfda::Application.routes.draw do
  

  get "home/disaster"
  get "home/apps"
  get "home/resources"
  get "home/network"
  get "home/aboutus"
  get "home/contact"
  get "home/work"
  get "home/valanteer"
  get "home/directory"
  resources :advertisements do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

  resources :news do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end


  resources :articles do
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

   resources :jobs do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
    get 'slider', on: :collection
  end


  get "optional/index"
  get "users/profile"
  get "users/index"
  get "users/show"
   get "users/settings"
  get "reports/index"
  get 'reports/db_upload'
    resources :reports
  #devise_for :users
  devise_for :users, controllers: { registration: 'registrations' }
  get "welcome/index"

   root 'jobs#slider'
   #root 'welcome#dashboard'
   get 'welcome/dashboard'
   get 'welcome/screener'
   get 'welcome/analytics'
   get 'welcome/optional'

   get '/users/subregion_options' => 'users#subregion_options'
   get '/payments/complete_payment' => 'payments#complete_payment'

resources :optionals do
  collection { post :import }
end 

resources :products do
  collection { post :import }
end 
resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
   resources :carts do
    collection do
      
      get :license_agrement
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
     if user.role? :user
        can :manage, Post
      end
      if user.role? :admin
        can :manage, ForumThread
      end
      if user.role? :superadmin
        can :manage, Forum
      end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end


end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
	belongs_to :user
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/article.rb
class Article < ActiveRecord::Base
	  belongs_to :user

	  
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/cities.rb
class Cities < ActiveRecord::Base
	belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :user


	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_many :news
    has_many :jobs
    has_many :advertisements
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def disaster
  end

  def apps
  end

  def resources
  end

  def network
  end

  def aboutus
  end

  def contact
  end

  def work
  end

  def valanteer
  end

  def directory
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/optional_helper.rb
module OptionalHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_about.html.erb
<h3>Our Firm</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been 
          the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing 
          Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
          It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>


<div class="clearfix"></div>


<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid" >
          <div class="span3 box" id="popup_window" data-popup-target="#example-popup1">
          <h5>Online Education</h5>
          	<div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "1.png"%></div>
              <div class="clearfix"></div>
              <div class="contentbx">You can access a wealth of education in the form of online training modules. Get yourself immediately up-to-speed and begin taking profitable trades as soon as you install your software....</div>
            </div>
          </div>
        <div class="span3 box"  id="popup_window" data-popup-target="#example-popup2">
          <h5>Lifetime Support</h5>
          	<div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "2.png" %></div>
              <div class="clearfix"></div>
              <div class="contentbx">As a HUBB member you can take advantage of lifetime Technical and Trading support. If you’re having troubles with your software or trading simply send us an email or logon to our chat 
            support to get the answers you are looking for.
          </div>
            </div>
          </div>
          <div class="span3 box"  id="popup_window" data-popup-target="#example-popup3">
          <h5>Free Upgrades</h5>
          	<div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "3.png" %></div>
              <div class="clearfix"></div>
              <div class="contentbx">Keep your software up-to-date and ready for the next big trading opportunity. Owners of IntegratedInvestor will have access to enhancements that improve the speed and functionality of your software.</div>
            </div>
          </div>
          <div class="span3 box" id="popup_window" data-popup-target="#example-popup4">
          <h5>Precomputed Trading<!--  Lists --></h5>
            <div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "4.png" %></div>
              <div class="clearfix"></div>
              <div class="contentbx">Open IntegratedInvestor and receive immediate access to the hottest long and short term trading opportunities. Pick your preferred strategies and instantly generate a list of the stocks to watch.e.</div>
            </div>
          </div>
        </div>
    </div>
</div> 
 <div class="clearfix"></div>

<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid" >
          
        <div class="span3 box"  id="popup_window" data-popup-target="#example-popup5">
          <h5>Technical Dashboard</h5>
            <div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "5.png" %></div>
               <div class="clearfix"></div>
              <div class="contentbx">Receive a proprietary summary of key technical indicators for any given stock. The Oscillator, Trend and Volume dials give you all you need to know at a glance.</div>
            </div>
          </div>
          <div class="span3 box"  id="popup_window" data-popup-target="#example-popup6">
          <h5>Fundamental Dashboard</h5>
            <div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "6.png" %></div>
               <div class="clearfix"></div>
              <div class="contentbx">
        Is your stock a Growth, Value or Income stock? Find out using our Fundamental Dashboard. This
            function allows you to quickly choose stocks that are suited to your style and eliminate those that aren’t.</div>
            </div>
          </div>
          <div class="span3 box" id="popup_window" data-popup-target="#example-popup7">
          <h5><!-- Broker  -->Recommendations</h5>
            <div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "box1.png" %></div>
               <div class="clearfix"></div>
              <div class="contentbx">Buy, sell or hold - what are the experts saying? Cross reference your own analysis with IntegratedInvestor’s inbuilt Broker Recommendations.</div>
            </div>
          </div>
        <div class="span3 box"  id="popup_window" data-popup-target="#example-popup8">
          <h5>News Headlines</h5>
            <div class="row-fluid">
              <div class="span12 imgbox"><%= image_tag "box2.png" %></div>
               <div class="clearfix"></div>
              <div class="contentbx">Knowledge is power – that’s why it’s essential that you know all you can about your company of interest. Our News feature makes this possible at the click of a button.</div>
            </div>
          </div>
         
        </div>
    </div>
</div> 



     
        </div>
    </div>
</div>

<script>
$(window).load(function(){
jQuery(document).ready(function ($) {
 
    $('[data-popup-target]').click(function () {
        $('html').addClass('overlay');
        var activePopup = $(this).attr('data-popup-target');
        $(activePopup).addClass('visible');
 
    });
 
    $(document).keyup(function (e) {
        if (e.keyCode == 27 && $('html').hasClass('overlay')) {
            clearPopup();
        }
    });
 
    $('.popup-exit').click(function () {
        clearPopup();
 
    });
 
    $('.popup-overlay').click(function () {
        clearPopup();
    });
 
    function clearPopup() {
        $('.popup.visible').addClass('transitioning').removeClass('visible');
        $('html').removeClass('overlay');
 
        setTimeout(function () {
            $('.popup').removeClass('transitioning');
        }, 200);
    }
 
});
});
</script>
<style>
#popup_window{
cursor: pointer;
}
.popup-overlay {
    width: 100%;
    height: 100%;
    position: fixed;
    background: rgba(196, 196, 196, .85);
    top: 0;
    left: 100%;
    opacity: 0;
    -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
    -webkit-transition: opacity .2s ease-out;
    -moz-transition: opacity .2s ease-out;
    -ms-transition: opacity .2s ease-out;
    -o-transition: opacity .2s ease-out;
    transition: opacity .2s ease-out;
}
.overlay .popup-overlay {
    opacity: 1;
    left: 0
}
.popup {
    position: fixed;
    top: 25%;
    left: 50%;
    z-index: -9999;
}
.popup .popup-body {
    background-color: #3F506B;
    color: #ffffff;
    opacity: 0;
    min-height: 150px;
    width: 400px;
    margin-left: -200px;
    padding: 20px;
    -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
    -webkit-transition: opacity .2s ease-out;
    -moz-transition: opacity .2s ease-out;
    -ms-transition: opacity .2s ease-out;
    -o-transition: opacity .2s ease-out;
    transition: opacity .2s ease-out;
    position: relative;
    -moz-box-shadow: 1px 2px 3px 1px rgb(185, 185, 185);
    -webkit-box-shadow: 1px 2px 3px 1px rgb(185, 185, 185);
    box-shadow: 1px 2px 3px 1px rgb(185, 185, 185);
    text-align: center;
    border: 1px solid #e9e9e9;
}
.popup.visible, .popup.transitioning {
    z-index: 9999;
}
.popup.visible .popup-body {
    opacity: 1;
    -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
}
.popup .popup-exit {
    cursor: pointer;
    display: block;
    width: 24px;
    height: 24px;
    position: absolute;
    top: -150px;
    right: -195px;
    background: url("/assets/quit.png") no-repeat;
 
}
.popup .popup-content {
    overflow-y: auto;
}
.popup-content .popup-title {
    font-size: 24px;
    border-bottom: 1px solid #e9e9e9;
    padding-bottom: 10px;
}
.popup-content p {
    font-size: 13px;
    text-align: justify;
}
</style>

  

app/views/welcome/_analytics.html.erb
<div style="padding:10px 0 15px 0;" class="list-height">
	<ul style="list-style: initial;">
		<li>Generate Option Chain  for a selected stock - chain should show all three expiry month options in horizontal side by side tables (like optionvue)</li>
		<li>Each month table should show strike, OI, bid/ask, volume, LTP, IV, which can be fetched from NSE, for the options for which IV is missing, IV will need to be interpolated.</li>
		<li>User should be able to sort by each column head – not needed if sorted by strike price like optionvue.</li>
		<li>User should be able to put a + or - quantity in any option row (like optionvue).</li>
		<li>Two graphs around the tables, one for skew, one for monthly term structure – will need to be plotted using the IV data NSE gives, IV for missing options will need to be interpolated. </li>
		<li>One user selects presses “analyze”, a strategy table should show payoffs, see option oracle payoff table, also a set of rows showing the options with greeks, quantity, margin, credit/debit and a total row. For margin, user can specify “NSE specified margin “ or overwrite it. Also, use should be able to specify brokerage.  Main expiry payoff graph will also have lines to capture time change. User should be able to select volatility change bands (like 2%) to see effect of volatility – see optionvue </li>
	</ul>
	
</div>

app/views/welcome/_dashboard.html.erb
    <h4> You did not have any Subcription. Please select Subcription below</h4>
        <% Subscription.all.each  do |sub| %>
        <section id="pricePlans">
        <ul id="plans">
            <li class="plan">
                <ul class="planContainer">
                    <li class="title"><h2 class="bestPlanTitle"><%=sub.subscription_type%></h2></li>
                    <li class="price"><p class="bestPlanPrice">$<%=sub.price%>/<span>month</span></p></li>
                    <li>
                        <ul class="options">
                            <li>2x <span>option 1</span></li>
                          
                            <li>Free <span>option 2</span></li>
                          
                            <li>Unlimited <span>option 3</span></li>
                          
                            <li>Unlimited <span>option 4</span></li>
                          
                            <li>1x <span>option 5</span></li>
                        </ul>
                    </li>
                    
                    <li class="button">
                        <%#= link_to("Purchase", payments_complete_payment_path(:subscription_id => sub, :subscription_type => sub.subscription_type)) %>
                        <%= link_to("Purchase", license_agrement_carts_path(:subscription_id => sub, :subscription_type => sub.subscription_type)) %>
                    </li>
                </ul>
            </li>
        </ul>
        <% end %>
    </section>

app/views/welcome/_screener.html.erb
<div style="padding:10px 0 15px 0;" class="list-height">
	<ul style="list-style: initial;">
		<li>User should be able to select strategy and expiry month from two dropdown lists and run screener.</li>
		<li>Will fetch a table with various columns – I will give this table. Sorting by columns is needed </li>
		<li>Select a row in the table and run analytics on that – which will show various tables, charts below – I will share what tables and  charts</li>
	</ul>
</div>

app/views/welcome/_tools.html.erb
<style>
.tab-new ul.nav-tabs li a{padding: 10px 15px;}
.tab-new ul.nav-tabs{height: 30px;}
</style>
<div class="container-fluid" style="background: #ffffff;">
    <h3>Our Tools</h3>
    	<div class="row tab-new">
		    
		        <ul class="nav nav-tabs container-fluid">
					<li><%= link_to "  Screener ", welcome_screener_path , :class=>"icon-film", :method => :get, :remote =>true %></li>
					<li>	<%= link_to "  Analytics ", welcome_analytics_path, :class=>" icon-tasks", :method => :get, :remote =>true %></li>
					<div class="clear"></div>
				</ul>

		    </div>


	  
	  <div class="container-fluid box3">
	      <%= render '/welcome/screener' %>
	</div>
</div>	
<!-- 
    <h4>The Ultimate Trade Finder</h4>
	<p>By fusing together the elements of fundamental studies, technical analysis, options analysis and consensus figures, IntegratedInvestor allows you to view a stock from every possible direction – taking out the risk and improving your probability of profitable trades! This immensely powerful piece of financial market analysis software is pioneering Integrated Analysis and is set to take your trading and investing to new heights!</p>
	<div class="how center"><%= image_tag "trade-finder.png" %></div>

	<h4>Integrated Scanner </h4>
	<p>The most sought after tool within the software, the Integrated Scanner allows you to scan the market for winning trades using a combination of technical, fundamental and options criteria – putting probability on your side.
		IntegratedInvestor is more than just the sum of its parts. Standalone ProfitSource, ValueGain and OptionGear are powerful platforms. Together they are a strong blend of technical, fundamental and options analysis tools. Combined with the new Integrated Analysis modules they form the most formidable piece of software on international markets.</p>
	<p>IntegratedInvestor is more than just the sum of its parts. Standalone ProfitSource,
	ValueGain and OptionGear are powerful platforms. Together they are a strong blend
	of technical, fundamental and options analysis tools. Combined with the new Integrated
	Analysis modules they form the most formidable piece of software on international
	markets
	</p>
	 <div class="row-fluid">
      <div class="span4">
        <div class="trade-box"><h5>ProfitSource</h5>
			<h6>The Edge for Active Investors!</h6>
			<ul>
			<li>Advanced technical analysis.</li>
			<li>Inbuilt Elliott Wave tools.</li>
			<li>Sophisticated scanning capabilities.</li>
			<li>Backtest your strategies to see what works.</li>
			<li>Hot stocks at the click of a button.</li>
			</ul>
		</div>
		<div class="trade-box" style="margin-top:10px; border: 2px solid #33689D;"><h5>ValueGain</h5>
			<h6>Fundamentals Made Easy!</h6>
			<ul>
			<li>Invest like the world’s best.</li>
			<li>Build your own fundamental scans.</li>
			<li>Broker ratings for individual stocks.</li>
			<li>Find the real value of any stock.</li>
			<li>Financial statements at a single click.</li>
			</ul>
		</div>
		<div class="trade-box" style="margin-top:10px; border: 2px solid #19A347;"><h5>OptionGear</h5>
			<h6>The Trading Profits Enhancer!</h6>
			<ul>
			<li>Advanced options analysis.</li>
			<li>Trade Scanner - what trades to take when.</li>
			<li>DIY scanning to find the best opportunities.</li>
			<li>Portfolio Manager to track your trades.</li>
			<li>View the volatility of a stock before you buy.</li>
			</ul>
		</div>
      	
      </div>
      <div class="span8">
      	<%= image_tag "trade-finder3.png", :style=> "width:500px; height:300px;" %>
		<%= image_tag "trade-finder4.png", :style=> "height: 300px;margin-left: -400px; margin-top: 175px;  position: absolute; width: 500px;" %>
		<%= image_tag "trade-finder5.png", :style=> "height: 300px;margin-left: -300px;margin-top: 320px;  position: absolute; width: 500px;" %>
      						
      </div>
    </div>
    <div class="row-fluid">
          <div class="span6 trade-box" style="margin-top:10px; border: 2px solid #AC8359;">
          	<h5>Comprehensive Market Data <br>World Markets at Your Fingertip</h5>
          	<p>Trading decisions are made on information. This information needs to be timely, accurate and
				consistent. IntegratedInvestor provides data for domestic and international markets allowing you to spot opportunities as they happen.</p>
          </div>
          <div class="span6 trade-box" style="margin-top:10px; border: 2px solid #AC8359;">
          	<h5>Comprehensive Market Data<br>World Markets at Your Fingertip</h5>
          	<p>The unique Futures/Forex module allows you to follow the underlying futures, interest rate and
				commodity markets – all of which are leading indicators of stock and sector performance.</p>
          </div>
        </div>
  </div>
</div> -->

app/views/welcome/dashboard.html.erb
<div class="row-fluid">
  <div class="span3">
    <div id='cssmenu'>
      <ul>
         <li class='active'>
          <%= link_to '<i class="icon-home"></i>&nbsp;Dashboard'.html_safe, welcome_dashboard_path, :method => :get, :remote =>true %>
        </li>

         <li class='last'>
          <%= link_to '<i class="icon-user"></i>&nbsp;Profile'.html_safe, users_profile_path, :method => :get, :remote =>true %>
        </li>
        
         <li class='has-sub'><a href='#'><i class="icon-fullscreen"></i>&nbsp;ARTICLES</a>
            <ul>
               <li><%#=link_to "Approved Articles", approved_articles_path, :remote => true %></li>
               <% if user_signed_in? && current_user.role == "admin"%>
               <li><%=link_to "Yet to Approved", preview_articles_path, :remote => true   %></li>
               <% end %>
               <% if user_signed_in? && current_user.role == "user"%>
               <li><%=link_to "My Articles", my_articles_path, :remote => true %></li>
               <% end %>
               <li><%=link_to "Create Article", new_article_path, :remote => true %></li>
               <li><%=link_to "All articles", all_articles_path, :remote => true %></li>
              
               
            </ul>
         </li>
         <li class='has-sub'><a href='#'><i class="icon-fullscreen"></i>&nbsp;NEWS&EVENTS</a>
            <ul>
               <li><%=link_to "All News", all_news_index_path, :remote => true %></li>
               <% if user_signed_in? && current_user.role == "admin"%>
               <li><%=link_to "Yet to Approve",preview_news_index_path, :remote => true %></li><% end %>
               <li><%=link_to "Create News", new_news_path, :remote => true %></li>
               <% if user_signed_in? && current_user.role == "user"%>
               <li><%=link_to "My News", my_news_index_path, :remote => true %></li><% end %>
               
            </ul>
         </li>
         <li class='has-sub'><a href='#'><i class="icon-th"></i>&nbsp;JOBS/TENDERS</a>
            <ul>
              
               <li><%=link_to "Approved JOBS", all_jobs_path, :remote => true %></li>
               <% if user_signed_in? && current_user.role == "admin"%>
               <li><%=link_to "Yet to Approve",preview_jobs_path, :remote => true  %></li><% end %>
               <li><%=link_to "Create Job", new_job_path, :remote => true %></li>
                <% if user_signed_in? && current_user.role == "user"%>
                <li><%=link_to "My Jobs", my_jobs_path, :remote => true %></li><% end %>
               
            </ul>
         </li>

         <li class='has-sub'><a href='#'><i class="icon-th"></i>&nbsp;ADVERTISEMENTS</a>
            <ul>
              
               <li><%=link_to "Approved Ads", all_advertisements_path, :remote => true %></li>
                <% if user_signed_in? && current_user.role == "admin"%>
               <li><%=link_to "Yet to Approve",preview_advertisements_path, :remote => true  %></li>
               <% end%>
               <li><%=link_to "Create Add", new_advertisement_path, :remote => true %></li>
               <% if user_signed_in? && current_user.role == "user"%>
               <li><%=link_to "My Adds", my_advertisements_path, :remote => true %></li><% end %>
            </ul>
         </li>



         <li class='last'><%#= link_to '<i class="icon-cog"></i>&nbsp;Settings'.html_safe, users_settings_path, :method => :get, :remote =>true %></li>
      </ul>
    </div>
    <!-- <div class="sidebar-nav">
        <div class="well">
            <ul class="nav nav-list">        
              <li style="height: 30px; margin: 10px">

                <%= link_to '<i class="icon-home"></i>Dashboard'.html_safe, welcome_dashboard_path, :method => :get, :remote =>true %></li>
              <li class="divider"></li>
              <li style="height: 30px; margin: 10px">
                <%= link_to '<i class="icon-envelope"></i>Profile'.html_safe, users_profile_path, :method => :get, :remote =>true %>
              <li class="divider"></li>
              <li  style="height: 30px; margin: 10px">
                <%= link_to '<i class="icon-comment"></i>Reports'.html_safe, reports_index_path, :method => :get, :remote =>true %></li>
              <li class="divider"></li>
              
              <li style="height: 30px; margin: 10px">
                <%= link_to '<i class="icon-cog"></i>Settings'.html_safe, users_settings_path, :method => :get, :remote =>true %></li>
            </ul>
        </div>
    </div> -->
  </div>

  
  <div class="span7 box3">
    <%#= render '/articles/index' %>
</div>
</div>

app/views/welcome/index.html.erb
<% render '/jobs/all1'%>


            
    <div id="tools">
      <%#= render '/welcome/tools' %>
    </div>
    <div id="firm">
        <%= render '/welcome/about' %>
    </div>  

app/views/welcome/optional.html.erb
<h3>Optional Analysis</h3>

<p>By analyzing the Options data, one can analyze the broad level trading range in the stock. Please note that NOT all the F&O stocks have liquid options, so be careful in buying/selling options of illiquid counters.<br>
Call with Highest Open Interest normally determines the price point for scrip which will not be easy to cross on the upside (Resistance).<br>
Put with Highest Open Interest normally determines the price point for scrip which will not be easy to cross on the downside (Support).<br>
Comparing the options data for a scrip with previous day(s) option data will give you insight of the change in trading range, whether the pressure is on the upside or downside.</p>
<% if user_signed_in? && current_user.role == "admin" %>
Admin
<% else %>
User
<%end %>