config/routes.rb
Srsfda::Application.routes.draw do
  

  get "home/disaster"
  get "home/apps"
  get "home/resources"
  get "home/network"
  get "home/aboutus"
  get "home/contact"
  get "home/work"
  get "home/valanteer"
  get "home/directory"
  resources :advertisements do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

  resources :news do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end


  resources :articles do
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
  end

   resources :jobs do 
    get 'preview', on: :collection
    get 'all', on: :collection
    get 'my', on: :collection
    get 'slider', on: :collection
  end


  get "optional/index"
  get "users/profile"
  get "users/index"
  get "users/show"
   get "users/settings"
  get "reports/index"
  get 'reports/db_upload'
    resources :reports
  #devise_for :users
  devise_for :users, controllers: { registration: 'registrations' }
  get "welcome/index"

   root 'jobs#slider'
   #root 'welcome#dashboard'
   get 'welcome/dashboard'
   get 'welcome/screener'
   get 'welcome/analytics'
   get 'welcome/optional'

   get '/users/subregion_options' => 'users#subregion_options'
   get '/payments/complete_payment' => 'payments#complete_payment'

resources :optionals do
  collection { post :import }
end 

resources :products do
  collection { post :import }
end 
resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
   resources :carts do
    collection do
      
      get :license_agrement
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
     if user.role? :user
        can :manage, Post
      end
      if user.role? :admin
        can :manage, ForumThread
      end
      if user.role? :superadmin
        can :manage, Forum
      end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end


end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
	belongs_to :user
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/article.rb
class Article < ActiveRecord::Base
	  belongs_to :user

	  
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/cities.rb
class Cities < ActiveRecord::Base
	belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :user


	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_many :news
    has_many :jobs
    has_many :advertisements
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/optional_helper.rb
module OptionalHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom"> 
    
    
  <div class="navbar-inner">
    <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a> 
      <div class="nav-collapse collapse pull-right">
        <ul class="nav pull-right">
        <li><%=link_to "ABOUT US", home_aboutus_path %></li>
        <li><%=link_to "VALANTEER WITH US", home_valanteer_path %></li>
        <li><%=link_to "WORK WITH US", home_work_path %></li>
        <li><%=link_to "CONTACT US", home_contact_path %></li>
        <li><%=link_to "DIRECTORY", home_directory_path %></li>
       </ul>

      </div>
    </div>
  </div>



    </div>

app/views/layouts/_logged_on.html.erb
<div class="navbar navbar-fixed-top"> 
    
    <div align="left" class="header">
      <div class="container">
        <div class="pull-right">
          <ul class="nav-top">
          <li><%= link_to "Dashboard", welcome_dashboard_path %></li>&nbsp;&nbsp;|&nbsp;&nbsp;
            <li><%= link_to "Reach Us", "#" %></li>&nbsp;&nbsp;|&nbsp;&nbsp;
           
            <li><%= link_to "LOGOUT", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </div>
        <div class="row">
          </br>
          <div class="span4"><span id="header-title">
              India<font color="#F7814D">Disaster Portal</font>
              <p class="header-sub">Geo Climate Risk Solutions Pvt Ltd </p>
            </span></div>
          <div class="span6">
            
          </div>
        </div>
     </div>
    </div>
  <div class="navbar-inner">
    <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a> 
      <div class="nav-collapse collapse pull-right">
        <ul class="nav pull-right">
          <li><%= link_to "HOME", root_path %></li>
          <li><%=link_to "DISASTER", home_disaster_path %></li>
          <li><%=link_to "APPS&TOOLS", home_apps_path %></li>
          <li><%=link_to "LINK&RESOURCES", home_resources_path %></li>
          <li><%=link_to "SOLUTIONS&ARTICLES", all_articles_path, :remote =>true %> 
          </li>
           <li><%=link_to "NEWS&EVENTS", all_news_index_path, :remote =>true %></li>
         
          <li><%=link_to "NETWORK", home_network_path %></li>
          <li><%= link_to "ADVERTISEMENT", all_advertisements_path, :remote =>true %></li>
           <li><%= link_to "JOBS/RFP's/TENDERS",all_jobs_path, :remote =>true %></li>
           

      </ul>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top"> 
    
    <div align="left" class="header">
      <div class="container">
        <div class="pull-right">
          <ul class="nav-top">
            <li><%= link_to "Reach Us", "#" %></li>&nbsp;&nbsp;|&nbsp;&nbsp;
            <li><%= link_to "Registration", new_user_registration_path %></li>&nbsp;&nbsp;|&nbsp;&nbsp;
            <li><%= link_to "Login", new_user_session_path %></li>
          </ul>
        </div>
        <div class="row">
          </br>
          <div class="span4"><span id="header-title">
              India<font color="#F7814D">Disaster Portal</font>
              <p class="header-sub">Geo Climate Risk Solutions Pvt Ltd </p>
            </span></div>
          <div class="span6">
            
          </div>
        </div>
     </div>
    </div>
  <div class="navbar-inner">
    <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a> 
      <div class="nav-collapse collapse pull-right">
        <ul class="nav pull-right">
          <li><%= link_to "HOME", root_path %></li>
          <li><%=link_to "DISASTER", home_disaster_path %></li>
          <li><%=link_to "APPS&TOOLS", home_apps_path %></li>
          <li><%=link_to "LINK&RESOURCES", home_resources_path %></li>
          <li><%=link_to "SOLUTIONS&ARTICLES", articles_path %></li>
          <li><%=link_to "NEWS&EVENTS", news_index_path %></li>
          <li><%=link_to "NETWORK", home_network_path %></li>
          <li><%= link_to "ADVERTISEMENT", advertisements_path %></li>
           <li><%= link_to "JOBS/RFP's/TENDERS", jobs_path %></li>
           

      </ul>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>India Disaster Portal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src='https://www.google.com/recaptcha/api.js'></script>

</head>
  <body>
   
      <% if current_user %>
        <%= render '/layouts/logged_on' %>
      <% else %>
        <%= render '/layouts/navigation' %>
      <% end %>
      <div id="content">
      <div class="container" >
        <%= flash_messages %>
      
      <%= yield %>
      </div>
    </div>
    </div>

 
    <%= render '/layouts/footer'%>

</div>
 </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Srsfda" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Srsfda</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>